### ISSUE TITLE
FYI Don't upgrade to Stack Heroku-16

### ISSUE THREAD

**Issue by unmultimedio** [davidakachaos/workless_revived#11]
In the settings section of an app in Heroku, there's now an option to upgrade to new Stack (if you were using old Cedar-14 Stack)

![estamos-liztum-chicos_ _settings___heroku](https://user-images.githubusercontent.com/4431392/27489211-53c2bf4e-57ff-11e7-9156-aa9a72036b45.gif)

In the [changelog of the new stack](https://devcenter.heroku.com/articles/heroku-16-stack), they state among the changes that the `HEROKU_` namespace for config vars is reserved, and its _recommended_ to not set variables with that namespace to avoid conflicts.

> The `HEROKU_` namespace is reserved for config vars set by the Heroku platform in order to offer functionality. If you have created HEROKU_ config vars, we suggest you change them when upgrading to Heroku-16, in order to avoid config var conflicts.

And as the setup of this gem requires:

> Add your Heroku app name / API key as config vars to your Heroku instance.
> `heroku config:add HEROKU_API_KEY=yourapikey APP_NAME=yourherokuappname`

It's better to avoid upgrading, at least until the gem supports a different config var name.

**Comment by davidakachaos** [comment]
Thank you for this report, I'll look into changing this config var to another name.

**Comment by davidakachaos** [comment]
I've released version 2.1.0 to address this issue. Can you verify the new version works correctly?
I've tested the new version in my own production apps and it I haven't encountered any errors.

**Comment by unmultimedio** [comment]
Hi @davidakachaos I've found another occurrence of the `HEROKU_API_KEY` in the [scaler](https://github.com/davidakachaos/workless_revived/blob/5531d7424d7675add47e4609ca3579e91af4b417/lib/workless/scaler.rb#L48) file. Should that be changed too?

**Comment by davidakachaos** [comment]
Please go to this issue on the [Workless](https://github.com/lostboy/workless/issues/) repository. Thank you!
