### ISSUE TITLE
Require specific heroku platform-api gem

### ISSUE THREAD

**Issue by yjukaku** [davidakachaos/workless_revived#16]
Just ran into an issue where I was getting app crashes until I manually ran `bundle update platform-api` (and `bundle update heroics`), because apparently I was on an old version of `platform-api`?

I think it might be a good idea to tie this gem to a specific version of `platform-api` that it has been tested with. 👍

**Comment by davidakachaos** [comment]
Yes it would be 😄 I'll make that happen soon.

**Comment by davidakachaos** [comment]
Please go to this issue on the [Workless](https://github.com/lostboy/workless/issues/) repository. Thank you!
