### ISSUE TITLE
Workless [message]

### ISSUE THREAD

**Issue by lostboy** [davidakachaos/workless_revived#17]
@davidakachaos thank you for taking the reigns on this, apologies for disappearing. If there's anything I can do for you, you want to merge back in or you wish to take over the gem name I'm happy to facilitate now i'm back in the coding world.

**Comment by davidakachaos** [comment]
Hello @lostboy ! Good to finally "meet" you 😄 Merging back this project into yours sounds like a good idea I think. If you want, I would love to help you maintain the original gem.
I hope we can work on this together moving forward. Let me know 😉

**Comment by lostboy** [comment]
@davidakachaos that sounds great
