### ISSUE TITLE
Middleware breaks streaming enumerator response_body

### ISSUE THREAD

**Issue by warnickr** [davidakachaos/workless_revived#2]
A common way to stream data such as a CSV file is to set the appropriate response headers and set the response_body to be an Enumerator that generates CSV data. The WorklessChecker middleware prevents this from working properly.

**Comment by davidakachaos** [comment]
Thanks for your report. I've adjusted the middleware to only check for scaling and nothing else. Could you see that branch and verify that it solves your bug?
